# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine
WORKDIR /app

# Install build tools and dependencies
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

RUN apk add --no-cache python3 make g++ \
    && npm ci --ignore-scripts \
    && npm run build \
    && npm prune --production \
    && apk del python3 make g++

# Default command for stdio usage
CMD ["node", "dist/index.js"]
